name: 'Build and Bake Docker Image'
description: 'Build and bake a Docker image'
inputs:
  tag:  # id of input
    description: 'Tag to apply to the image'
    required: true
    default: 'latest'
  package-name:
    description: 'Name of the package to build'
    required: true
  target-registry:
    description: 'Target registry to push the image to'
    required: true
  repository-username:
    description: 'Repository username'
    required: true
  repository-password:
    description: 'Repository password'
    required: true
  source:
    description: 'Source directory to build the image from'
    required: true
    default: '.'
  workDir:
    description: 'Working directory to build the image from'
    required: true
    default: '.'
  files:
    description: 'Files to include in the image'
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.target-registry }}
        username: ${{ inputs.repository-username }}
        password: ${{ inputs.repository-password }}

    - name: Build and Bake Docker Image
      uses: docker/bake-action@v6
      with:
        source: ${{ inputs.source }}  
        workDir: ${{ inputs.workDir }}
        files:
          "./docker-bake.hcl"
        push: ${{ !env.ACT }}
        pull: ${{ !env.ACT }}
        tags: ${{ inputs.target-registry }}/${{ github.actor }}/${{ inputs.package-name }}:${{ inputs.tag }}
        targets: 
          ${{ inputs.package-name }}
